[workspace]
members = [
    'runtime/moonbeam',
    'runtime/moonriver',
    'runtime/moonshadow',
    'runtime/moonbase',
    'node',
    'node/cli',
    'node/service',
    'bin/utils/moonkey',
    'bin/moonbasic',
]
exclude = ['bin/utils/moonkey']

[profile.release]
panic = 'unwind'
